sp = float(67836.43)
rj = float(36678.66)
mg = float(29229.88)
es = float(27165.48)
outros = float(19849.53)
total = float(sp + rj + mg + es + outros)
print(total)
psp = ((sp/total)*100)
prj = ((rj/total)*100)
pmg = ((mg/total)*100)
pes = ((es/total)*100)
poutros = ((outros/total)*100)

print('Percentual de São Paulo: {}'.format(psp))
print('Percentual do Rio de Janeiro: {}'.format(prj))
print('Percentual de Minas Gerais: {}'.format(pmg))
print('Percentual do Espírito Santo: {}'.format(pes))
print('Percentual dos demais estados: {}'.format(poutros))